apiVersion: v1
kind: Service
metadata:
  name: fastapi-pytorch-mnist-service
spec:
  selector:
    app.kubernetes.io/name: fastapi-pytorch-mnist
  ports:
    - protocol: HTTP
      port: 80
      targetPort: 9376
